model_type: yoloV3
label_file: /media/ubuntu/data1/YoloV3/json_label.yaml
num_class: 7
input_config:
  record_path: /media/ubuntu/data1/YoloV3/train.record
  batch_size: 32
batch_size: 32

hyperparams:
  batch_norm:
    center: True
    scale: True
    is_training: True
    decay: 0.9997
    epsilon: 0.001
    train: True
  regularizer:
    type: l2_regularizer
    weigth: 0.00004
  initializer:
    type: truncated_normal_initializer
    mean: 0.0
    stddev: 0.009
  activation:
    type: Relu_6
    #alpha: 0.1
  #不使用偏置则不填写
  use_bias: 0.0

box_predictor:
  use_dropout: false
  kernel_size: 3
  coder_size: 4
  dropout_keep_prob: 0.8
  apply_sigmoid_to_scores: false
  class_prediction_bias_init: 0.01
  confidence_prediction_bias_init: 0.1
  use_depthwise: true
Matcher:
  matched_threshold: 0.5
  unmatched_threshold: 0.5
#(10*13); (16*30); (33*23); (30*61); (62*45); (59*119); (116*90); (156*198); (373*326)
Anchors: [[[24,14],[28,19],[32,20]],[[41,23],[46,63],[122,160]]]
num_anchors: 3
iou_threshold: 0.5
classfication_loss:
  loss_type: weighted_sigmoid
cls_weigth: 1.0

localfication_loss:
  loss_type: weighted_smooth_l1
  delta: 1.0
loc_weigth: 1.0

confidence_loss:
  loss_type: Cross_Entropy_Loss
  no_obj_weigth: 5.0
confidence_weigth: 5.0
add_regularization_loss: true

hard_example:
  iou_threshold: 0.99
  num_hard_examples: 1000
  max_negatives_per_positive: 3
  min_negatives_per_image: 3
  loss_type: cls
  loc_weigth: 1.0
  cls_weigth: 1.0
  obj_weigth: 1.0

optimizer:
  type: rms_prop_optimizer
  rms_prop_optimizer:
    learning_rate:
      type: exponential_decay_learning_rate
      initial_learning_rate: 0.0035
      decay_steps: 80000
      decay_factor: 0.95
      staircase: False
  momentum_optimizer_value: 0.9
  decay: 0.9
  epsilon: 1.0

use_moving_averages: False
average_decay: 0.9999

post_process:
  NMS:
    iou_threshold: 0.3
    max_class_detection: 50
    scores_threshold: 0.0
    max_detection: 50
  score_convert:
    type: SIGMOID
    logit_scale: 1.0
#不填写表示一直训练
num_steps: 100000
keep_checkpoint_every_n_hours: 500
resize: [416,416]
scale:  [13,13]
